### ISSUE TITLE
Upgrading capquiz breaks the block

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-block_capquizqtracker#1]
**To reproduce**

Install capquiz is upgraded beyond v0.5.0, set up the tracker block, and accumulate data from several students (both questions and comments).

Upgrade capquiz so that the question_usage_by_activity is split to get one object per student.

**What happens**
A student entering the quiz gets an error message (see https://github.com/KQMATH/moodle-mod_capquiz)
The stack trace (debugging mode) shows that it is triggered by the block and not by capquiz.

**Comments**
Removing the block solves the problem.
I have not tested if the block works with the new version of capquiz without upgrading.

**Comment by davrikn** [comment]
Tested and the issue no longer occurs

**Comment by hgeorgsch** [comment]
Did you really do a full test, making a quiz, with questions, student attempts, and issues in a version before 0.5, and then upgrade?

It does not overly matter though, since qtracker has not been released.  There is no need to make it backwards compatible,

**Comment by davrikn** [comment]
I came across the problem while testing capquizqtracker, the capquiz worked fine (adding questions, doing quizzes etc) until the capquizqtracker block was added. Once the block was added the quba error occured (only when entering the quiz as a student, removing the block while being logged in as an admin also fixed it, but then you would be without qtracker), after checking out this branch the quba error was gone, and quizzes could be performed as normal.

I did not test upgrading from an earlier version of capquiz
